object Errors:
  object Impossible extends Exception("impossible")

  final case class UnifyError(msg: String)
      extends Exception(s"unify error: $msg")

  final case class ElabUnifyError(msg: String)
      extends Exception(s"unify error: $msg")
  final case class CannotInferError(msg: String)
      extends Exception(s"cannot infer: $msg")
  final case class ExpectedSigmaError(msg: String)
      extends Exception(s"expected a sigma type: $msg")
  final case class UndefinedVarError(msg: String)
      extends Exception(s"undefined variable: $msg")
  final case class HoleFoundError(msg: String)
      extends Exception(s"hole found: $msg")
  final case class NamedImplicitError(msg: String)
      extends Exception(s"named implicit: $msg")
  final case class IcitMismatchError(msg: String)
      extends Exception(s"icit mismatch: $msg")
  final case class UnsolvedMetasError(msg: String)
      extends Exception(s"unsolved metas: $msg")
