object Errors:
  final case class Impossible() extends Exception(s"impossible")
  final case class UnifyError(msg: String)
      extends Exception(s"unify error: $msg")

  final case class ElaborationUnifyError(msg: String)
      extends Exception(s"unify error: $msg")
  final case class CannotInferError(msg: String)
      extends Exception(s"cannot infer: $msg")
  final case class NotPiError(msg: String) extends Exception(s"not a pi: $msg")
  final case class NotSigmaError(msg: String)
      extends Exception(s"not a sigma: $msg")
  final case class VarError(msg: String)
      extends Exception(s"undefined variable: $msg")
  final case class GlobalError(msg: String)
      extends Exception(s"duplicate global: $msg")
  final case class HoleError(msg: String) extends Exception(s"hole found: $msg")
  final case class UnsolvedMetasError(msg: String)
      extends Exception(s"unsolved metas: $msg")
  final case class NameNotInPiError(msg: String)
      extends Exception(s"name not found in pi: $msg")
  final case class AppIcitMismatchError(msg: String)
      extends Exception(s"app icit mismatch: $msg")
  final case class NamedLambdaError(msg: String)
      extends Exception(s"cannot infer named lambda: $msg")
